import {
	faSort,
	faEye,
	faArrowCircleLeft,
	faArrowCircleRight,
	faArrowAltCircleRight,
	faArrowAltCircleLeft,
	faClock,
	faSearch,
	faPlay,
	faAngleLeft,
	faAngleRight,
	faHeart
} from '@fortawesome/free-solid-svg-icons';

import {
	faChevronLeft,
	faChevronRight,
	faListUl,
	faThLarge,
	faShoppingCart,
	faExpand,
	faAngleDoubleLeft,
	faAngleDoubleRight,
	faEllipsisH,
	faReply
} from '@fortawesome/pro-solid-svg-icons';

import {
	faPhone,
	faCheck,
	faMapMarkerAlt,
	faEnvelopeOpen,
	faMap,
	faEnvelope,
	faPaperPlane,
	faHeadphones,
	faCopyright,
	faStar,
	faBars,
	faTimes,
	faWindowClose,
	faLongArrowRight,
	faUser,
	faComments,
	faCalendarCheck,
} from '@fortawesome/pro-regular-svg-icons';

import {
	faUsers,
	faTrophyAlt,
	faAngleDown,
	faCalendar,
	faLongArrowLeft,
	faGem,
	faLaptopCode,
	faAnalytics,
	faFingerprint,
	faHeadSideBrain,
	faAtomAlt,
	faBoxCheck,
} from '@fortawesome/pro-light-svg-icons';


import {
	faFacebookF,
	faFacebook,
	faGoogle,
	faGooglePlus,
	faInstagram,
	faLinkedin,
	faPinterest,
	faTwitter,
	faBehance,
	faYoutube,
	faLinkedinIn,
	faGooglePlusG
} from '@fortawesome/free-brands-svg-icons';

import {library} from '@fortawesome/fontawesome-svg-core';

export const loadIcons = () => {
	library.add(
		faSort,
		faEye,
		faBars,
		faArrowCircleLeft,
		faArrowCircleRight,
		faArrowAltCircleLeft,
		faArrowAltCircleRight,
		faClock,
		faBoxCheck,
		faHeart,
		faUsers,
		faTrophyAlt,
		faAngleDown,
		faUser,
		faCalendar,
		faComments,
		faLongArrowLeft,
		faGem,
		faLaptopCode,
		faAnalytics,
		faFingerprint,
		faHeadSideBrain,
		faAtomAlt,
		faSearch,
		faPhone,
		faChevronLeft,
		faChevronRight,
		faCheck,
		faListUl,
		faThLarge,
		faShoppingCart,
		faExpand,
		faAngleDoubleLeft,
		faAngleDoubleRight,
		faEllipsisH,
		faReply,
		faPlay,
		faLongArrowRight,
		faMapMarkerAlt,
		faEnvelopeOpen,
		faStar,
		faFacebook,
		faFacebookF,
		faGooglePlus,
		faTwitter,
		faInstagram,
		faLinkedin,
		faGoogle,
		faPinterest,
		faYoutube,
		faBehance,
		faMap,
		faEnvelope,
		faPaperPlane,
		faHeadphones,
		faLinkedinIn,
		faGooglePlusG,
		faCopyright,
		faTimes,
		faCalendarCheck,
		faWindowClose,
		faAngleLeft,
		faAngleRight,
	);
};
